name: bintango_indonesian_translater
description: Bintango indonesian translater for web
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.0
  riverpod_annotation: 2.3.5
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: 7.0.1
  shared_preferences: ^2.0.15
  google_fonts: ^4.0.1
  lottie: ^2.2.0
  connectivity_plus: ^3.0.2
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.10+1
  go_router: ^6.0.3
  easy_localization: ^3.0.7
  firebase_core: ^2.31.0
  firebase_analytics: ^10.10.5
  app_tracking_transparency: ^2.0.5
  json_annotation: ^4.9.0
  auto_size_text: ^3.0.0
  supabase_flutter: ^2.5.3
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.2.6
  responsive_framework: ^1.4.0
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.7
  build_verify: any
  flutter_gen_runner: any
  freezed: ^2.4.5
  go_router_builder: ^2.4.1
  import_sorter: ^4.6.0
  json_serializable: any
  pubspec_dependency_sorter: ^1.0.4
  riverpod_generator: ^2.3.8
  very_good_analysis: 4.0.0+1
  rename: ^3.0.2
  flutter_launcher_icons: ^0.13.1

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    inputs:
      - assets/color/colors.xml
    enabled: true
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/.env.development
    - assets/env/
    - assets/
    - assets/image/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
